#!/usr/bin/env python3
"""Embed source in ConfigMap manifests. Requires only Python's standard library."""
from pathlib import Path
from textwrap import indent

ROOT = Path(__file__).resolve().parent
PREFIX = '''# Generated by build_manifests.py; edit source, then regenerate.
apiVersion: v1
kind: Namespace
metadata:
  name: turtle-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: turtle-app
  namespace: turtle-demo
data:
'''
WORKLOAD = '''---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turtle-data
  namespace: turtle-demo
spec:
  accessModes: [ReadWriteOnce]
  # Uncomment and set if there is no default StorageClass.
  # storageClassName: YOUR_STORAGE_CLASS
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtle
  namespace: turtle-demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: turtle
  template:
    metadata:
      labels:
        app: turtle
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 15
      securityContext:
        runAsNonRoot: true
__IDENTITY__        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: turtle
          # Source is mounted from the ConfigMap. No custom image build required.
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          command: [python, /app/app.py]
          env:
            - name: DATA_DIR
              value: /data
            - name: PVC_NAME
              value: turtle-data
            - name: STEP_SECONDS
              value: "1"
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 192Mi
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: code
          configMap:
            name: turtle-app
        - name: data
          persistentVolumeClaim:
            claimName: turtle-data
---
apiVersion: v1
kind: Service
metadata:
  name: turtle
  namespace: turtle-demo
spec:
  selector:
    app: turtle
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
'''


def main():
    config = PREFIX
    for name in ('app.py', 'index.html'):
        config += f'  {name}: |\n' + indent((ROOT / name).read_text(), '    ') + '\n'
    output = ROOT / 'k8s'
    output.mkdir(exist_ok=True)
    # Generic Kubernetes needs a non-root UID and a writable CSI volume group.
    identity = '        runAsUser: 10001\n        runAsGroup: 10001\n        fsGroup: 10001\n        fsGroupChangePolicy: OnRootMismatch\n'
    (output / 'turtle-pv-demo.yaml').write_text(config + WORKLOAD.replace('__IDENTITY__', identity))
    # OpenShift restricted-v2 SCC supplies both the UID and permitted fsGroup.
    (output / 'turtle-pv-demo-openshift.yaml').write_text(config + WORKLOAD.replace('__IDENTITY__', ''))
    print('Generated Kubernetes and OpenShift manifests')


if __name__ == '__main__':
    main()
